WITH RECURSIVE HOUR_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM HOUR_TABLE WHERE HOUR < 23
)
SELECT HOUR_TABLE.HOUR, COUNT(ANIMAL_ID) AS COUNT
FROM HOUR_TABLE
LEFT JOIN ANIMAL_OUTS
    ON HOUR(ANIMAL_OUTS.DATETIME) = HOUR_TABLE.HOUR
GROUP BY HOUR_TABLE.HOUR
ORDER BY HOUR_TABLE.HOUR;